name: paradrop-governor
version: 0.1
summary: Paradrop Governor is a service that enables device administration.
description: |
  The Paradrop Governor is a small service designed to help with
  administration tasks on deployed Ubuntu Core systems.

confinement: devmode
grade: stable

apps:
  governor:
    command: governor
    daemon: simple
    environment:
      GOVERNOR_SOCKET: $SNAP_COMMON/governor.socket
    plugs:
      - network
      - network-bind

parts:
  go:
    source-tag: go1.10.4
  governor:
    after: [go]
    plugin: go
    source: https://github.com/ParadropLabs/governor.git
    go-importpath: github.com/ParadropLabs/governor

slots:
  governor-control:
    interface: content
    write:
      - $SNAP_COMMON
